JN_WEB/JN_WEB/Controllers/CarritoController.cs
using JN_WEB.Entities;
using JN_WEB.Interfaces;
using JN_WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace JN_WEB.Controllers
{
    public class CarritoController : Controller
    {
        private readonly ICarritoModel _carritoModel;

        public CarritoController(ICarritoModel carritoModel)
        {
            _carritoModel = carritoModel;
        }

        [HttpGet]
        public IActionResult AgregarCursoCarrito(long q)
        {
            CarritoEnt entidad = new CarritoEnt();
            entidad.IdCurso = q;

            _carritoModel.AgregarCursoCarrito(entidad);
            var datosCarrito = _carritoModel.ConsultarResumenCarrito();

            HttpContext.Session.SetString("Cantidad", datosCarrito?.Objeto.Cantidad.ToString());
            HttpContext.Session.SetString("SubTotal", datosCarrito?.Objeto.SubTotal.ToString());

            return RedirectToAction("PantallaPrincipal", "Home");
        }
    }
}

JN_WEB/JN_WEB/Controllers/HomeController.cs
using AspNetCore.ReCaptcha;
using JN_WEB.Entities;
using JN_WEB.Interfaces;
using JN_WEB.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace JN_WEB.Controllers
{
    [ValidateReCaptcha]
    public class HomeController : Controller
    {
        private readonly IUsuariosModel _usuariosModel;
        private readonly ICursosModel _cursosModel;
        private readonly ICarritoModel _carritoModel;

        public HomeController(IUsuariosModel usuariosModel, ICursosModel cursosModel, ICarritoModel carritoModel)
        {
            _usuariosModel = usuariosModel;
            _cursosModel = cursosModel;
            _carritoModel = carritoModel;
        }


        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult IniciarSesion(UsuarioEnt entidad)
        {
            try
            {
                entidad.Contrasenna = _usuariosModel.Encrypt(entidad.Contrasenna);
                var datos = _usuariosModel.IniciarSesion(entidad);
                if (datos?.Codigo != 1)
                {
                    ViewBag.Mensaje = datos?.Mensaje;
                    return View("Index");
                }

                HttpContext.Session.SetString("TokenUsuario", datos.Objeto.Token.ToString());
                HttpContext.Session.SetString("NombreUsuario", datos.Objeto.Nombre.ToString());
                HttpContext.Session.SetString("RolUsuario", datos.Objeto.IdRol.ToString());
                HttpContext.Session.SetString("NombreRolUsuario", datos.Objeto.NombreRol.ToString());

                if (datos?.Objeto.ContrasennaTemp == true)
                {
                    return RedirectToAction("Cambiar", "Home");
                }

                return RedirectToAction("PantallaPrincipal", "Home");

            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Consulte con el administrador";
                return View("Index");
            }
        }



        [HttpGet]
        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegistrarUsuario(UsuarioEnt entidad)
        {
            entidad.Contrasenna = _usuariosModel.Encrypt(entidad.Contrasenna);
            var datos = _usuariosModel.RegistrarUsuario(entidad);
            if (datos?.Codigo != 1)
            {
                ViewBag.Mensaje = datos?.Mensaje;
                return View("Registro");
            }

            return RedirectToAction("Index", "Home");
        }



        [HttpGet]
        public IActionResult Recuperar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RecuperarContrasenna(UsuarioEnt entidad)
        {
            var datos = _usuariosModel.RecuperarContrasenna(entidad);
            if (datos?.Codigo != 1)
            {
                ViewBag.Mensaje = datos?.Mensaje;
                return View("Recuperar");
            }

            return RedirectToAction("Index", "Home");
        }



        [HttpGet]
        public IActionResult Cambiar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CambiarContrasenna(UsuarioEnt entidad)
        {
            entidad.Contrasenna = _usuariosModel.Encrypt(entidad.Contrasenna);

            if (entidad.Contrasenna == entidad.ContrasennaTemporal)
            {
                ViewBag.Mensaje = "Las contraseñas no pueden ser iguales";
                return View("Cambiar");
            }

            var datos = _usuariosModel.CambiarContrasenna(entidad);
            if (datos?.Codigo != 1)
            {
                ViewBag.Mensaje = datos?.Mensaje;
                return View("Cambiar");
            }

            return RedirectToAction("PantallaPrincipal", "Home");
        }



        [HttpGet]
        public IActionResult CambiarContrasennaUsuario()
        {
            HttpContext.Session.SetString("NombrePantalla", "Cambiar Contraseña");
            return View();
        }

        [HttpPost]
        public IActionResult CambiarContrasennaUsuario(UsuarioEnt entidad)
        {
            entidad.Contrasenna = _usuariosModel.Encrypt(entidad.Contrasenna);
            entidad.ConfirmarContrasenna = _usuariosModel.Encrypt(entidad.ConfirmarContrasenna);

            if (entidad.Contrasenna != entidad.ConfirmarContrasenna)
            {
                ViewBag.Mensaje = "Las contraseñas no coinciden";
                return View("CambiarContrasennaUsuario");
            }

            var datos = _usuariosModel.CambiarContrasenna(entidad);
            if (datos?.Codigo != 1)
            {
                ViewBag.Mensaje = datos?.Mensaje;
                return View("CambiarContrasennaUsuario");
            }

            return RedirectToAction("PantallaPrincipal", "Home");
        }



        [HttpGet]
        public IActionResult PantallaPrincipal()
        {
            HttpContext.Session.SetString("NombrePantalla", "Cursos Disponibles");
            var datos = _cursosModel.ConsultarCursos();

            var datosCarrito = _carritoModel.ConsultarResumenCarrito();

            HttpContext.Session.SetString("Cantidad", datosCarrito?.Objeto.Cantidad.ToString());
            HttpContext.Session.SetString("SubTotal", datosCarrito?.Objeto.SubTotal.ToString());

            return View(datos?.Objetos);
        }



        [HttpGet]
        public IActionResult CerrarSesion()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JN_WEB/JN_WEB/Views/Home/Cambiar.cshtml
@model JN_WEB.Entities.UsuarioEnt

@{
    ViewData["Title"] = "Cambiar";
    Layout = "~/Views/Shared/_Layout - Inicio.cshtml";
}

<span class="mask bg-gradient-dark opacity-6"></span>
<div class="container my-auto">
    <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                        <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">JN WEB</h4>
                    </div>
                </div>

                <div class="card-body">

                    @using (Html.BeginForm("CambiarContrasenna", "Home", FormMethod.Post, new { @class = "text-start" }))
                    {
                        <div class="input-group input-group-outline mb-3">
                            @Html.TextBoxFor(x => x.ContrasennaTemporal, new { @class="form-control", @type="password", @placeholder="Contraseña Temporal" })
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            @Html.TextBoxFor(x => x.Contrasenna, new { @class="form-control", @type="password", @placeholder="Contraseña" })
                        </div>

                        @if (ViewBag.Mensaje != null)
                        {
                            <div style="text-align:center" class="alert alert-light" role="alert">
                                @ViewBag.Mensaje
                            </div>
                        }
 
                        <div class="text-center">
                            <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Confirmar</button>
                        </div>
 
                    }
                </div>
            </div>
        </div>
    </div>
</div>

JN_WEB/JN_WEB/Views/Home/CambiarContrasennaUsuario.cshtml
@model JN_WEB.Entities.UsuarioEnt

@{
    ViewData["Title"] = "Cambiar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("CambiarContrasennaUsuario", "Home", FormMethod.Post, new { @class = "text-start" }))
{
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="card card-plain col-lg-8">

            <div class="card-body">
                @Html.Label("Contraseña")   
                <div class="input-group input-group-outline mb-3">
                    @Html.TextBoxFor(x => x.Contrasenna, new { @class="form-control", @type="password", @placeholder="Contraseña" })
                </div>

                @Html.Label("Confirmar Contraseña")
                <div class="input-group input-group-outline mb-3">
                    @Html.TextBoxFor(x => x.ConfirmarContrasenna, new { @class="form-control", @type="password", @placeholder="Confirmar Contraseña" })
                </div>

                @if (ViewBag.Mensaje != null)
                {
                    <div style="text-align:center" class="alert alert-light" role="alert">
                        @ViewBag.Mensaje
                    </div>
                }

                <div style="text-align:right">
                    <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0" style="width:25%!important">Confirmar</button>
                </div>
            </div>
        </div>
    </div>
}

JN_WEB/JN_WEB/Views/Home/Index.cshtml
@model JN_WEB.Entities.UsuarioEnt

@{
    ViewData["Title"] = "Inicio";
    Layout = "~/Views/Shared/_Layout - Inicio.cshtml";
}
@using AspNetCore.ReCaptcha
@Html.ReCaptcha()

<span class="mask bg-gradient-dark opacity-6"></span>
<div class="container my-auto">
    <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                        <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">JN WEB</h4>
                    </div>
                </div>
                <div class="card-body">

                    @using (Html.BeginForm("IniciarSesion", "Home", FormMethod.Post, new { @class = "text-start" }))
                    {
                        <div class="input-group input-group-outline my-3">
                            @Html.TextBoxFor(x => x.CorreoElectronico, new { @class="form-control", @placeholder="Correo Electrónico" })
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            @Html.TextBoxFor(x => x.Contrasenna, new { @class="form-control", @type="password", @placeholder="Contraseña", /*@onpaste="return false;", @ondrop="return false;"*/ })
                        </div>

                        @if (ViewBag.Mensaje != null)
                        {
                            <div style="text-align:center" class="alert alert-light" role="alert">
                                @ViewBag.Mensaje
                            </div>
                        }

                        <div class="text-center">
                            <button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">Iniciar Sesión</button>
                        </div>
                        <p class="mt-4 text-sm text-center">
                            ¿Olvidaste la contraseña?
                            <a href="@Url.Action("Recuperar","Home")" class="text-primary text-gradient font-weight-bold">Recuperar Contraseña</a>
                            <br />
                            ¿No tienes una cuenta?
                            <a href="@Url.Action("Registro","Home")" class="text-primary text-gradient font-weight-bold">Ir al Registro</a>
                        </p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

JN_WEB/JN_WEB/Views/Home/PantallaPrincipal.cshtml
@model IEnumerable<JN_WEB.Entities.CursoEnt>

@{
    ViewData["Title"] = "Pantalla Principal";
}

<div class="row">

    @if (Model.Count() > 0)
    {

        @foreach (var item in Model)
        {
            <div class="col-lg-3">
                <div class="card">

                    <img src="@item.Imagen" class="card-img-top" alt="..." />

                    <div class="card-body">
                        <h5 class="card-title">@item.Nombre</h5>
                        <p class="card-text">
                            Instructor: @item.Instructor
                            <br /> @item.FechaInicio.ToShortDateString() - @item.Finalizacion.ToShortDateString()
                            <br /> Espacios: @item.Cupo
                            <br /> Precio: $ @item.Precio
                        </p>

                        <div class="row">
                            <div class="col-1"></div>
                            <div class="col-5">
                                <a href="@Url.Action("AgregarCursoCarrito", "Carrito", new { q = item.IdCurso })" class="btn btn-outline-info"><i class="fa fa-plus"></i>  Añadir</a>
                            </div>
                            <div class="col-5">
                                <a href="" class="btn btn-outline-info"><i class="fa fa-list"></i>  Detalle</a>
                            </div>
                        </div>

                    </div>

                </div>
                <br /><br />
            </div>
        }

    }
    else
    {
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <div class="card">

                <div class="card-body">
                    <h5 class="card-title" style="text-align:center">No hay cursos disponibles en este momento</h5>
                </div>

            </div>
            <br /><br />
        </div>
    }

</div>

JN_WEB/JN_WEB/Views/Home/Recuperar.cshtml
@model JN_WEB.Entities.UsuarioEnt

@{
    ViewData["Title"] = "Recuperar";
    Layout = "~/Views/Shared/_Layout - Inicio.cshtml";
}

<span class="mask bg-gradient-dark opacity-6"></span>
<div class="container my-auto">
    <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                        <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">JN WEB</h4>
                    </div>
                </div>
                <div class="card-body">

                    @using (Html.BeginForm("RecuperarContrasenna", "Home", FormMethod.Post, new { @class = "text-start" }))
                    {
                        <div class="input-group input-group-outline my-3">
                            @Html.TextBoxFor(x => x.CorreoElectronico, new { @class="form-control", @placeholder="Correo Electrónico" })
                        </div>

                        @if (ViewBag.Mensaje != null)
                        {
                            <div style="text-align:center" class="alert alert-light" role="alert">
                                @ViewBag.Mensaje
                            </div>
                        }
                       
                        <div class="text-center">
                            <button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">Recuperar Contraseña</button>
                        </div>
                        <p class="mt-4 text-sm text-center">
                            ¿tienes una cuenta?
                            <a href="@Url.Action("Index","Home")" class="text-primary text-gradient font-weight-bold">Ir al Inicio</a>
                        </p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

JN_WEB/JN_WEB/Views/Home/Registro.cshtml
@model JN_WEB.Entities.UsuarioEnt

@{
    ViewData["Title"] = "Registro";
    Layout = "~/Views/Shared/_Layout - Inicio.cshtml";
}

<span class="mask bg-gradient-dark opacity-6"></span>
<div class="container my-auto">
    <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                        <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">JN WEB</h4>
                    </div>
                </div>
                <div class="card-body">

                    @using (Html.BeginForm("RegistrarUsuario", "Home", FormMethod.Post, new { @class = "text-start" }))
                    {
                        <div class="input-group input-group-outline mb-3">
                            @Html.TextBoxFor(x => x.Identificacion, new { @class="form-control", @type="text", @placeholder="Identificación", @onchange="BuscarNombre();" })
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            @Html.TextBoxFor(x => x.Nombre, new { @class="form-control", @disabled="true", @type="text", @placeholder="Nombre" })
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            @Html.TextBoxFor(x => x.CorreoElectronico, new { @class="form-control", @placeholder="Correo Electrónico" })
                        </div>
                        <div class="input-group input-group-outline mb-3">
                            @Html.TextBoxFor(x => x.Contrasenna, new { @class="form-control", @type="password", @placeholder="Contraseña" })
                        </div>
                        <div class="form-check form-check-info text-start ps-0">
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" checked>
                            <label class="form-check-label text-dark font-weight-bolder" for="flexCheckDefault">
                                Acepto los términos y condiciones.
                            </label>
                        </div>

                        @if (ViewBag.Mensaje != null)
                        {
                            <div style="text-align:center" class="alert alert-light" role="alert">
                                @ViewBag.Mensaje
                            </div>
                        }

                        <div class="text-center">
                            <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Registrarse</button>
                        </div>
                        <p class="mt-4 text-sm text-center">
                            ¿tienes una cuenta?
                            <a href="@Url.Action("Index","Home")" class="text-primary text-gradient font-weight-bold">Ir al Inicio</a>
                        </p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/buscarid.js"></script>