JN_WEB/JN_WEB/Controllers/CursoController.cs
using Microsoft.AspNetCore.Mvc;

namespace JN_WEB.Controllers
{
    public class CursoController : Controller
    {
        [HttpGet]
        public IActionResult ConsultarCursosUsuario()
        {
            return View();
        }
    }
}

JN_WEB/JN_WEB/Views/Shared/_Layout - Inicio.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/favicon.png">
    <title>JN WEB</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <link id="pagestyle" href="~/assets/css/material-dashboard.css?v=3.1.0" rel="stylesheet" />
    <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
</head>

<body class="bg-gray-200">
    
    <main class="main-content  mt-0">
        <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
            
            @RenderBody()
            
            <footer class="footer position-absolute bottom-2 py-2 w-100">
                <div class="container">
                    <div class="row align-items-center justify-content-lg-between">
                        <div class="col-12 col-md-12 my-auto">
                            <div class="copyright text-center text-sm text-white text-lg-start">
                                @DateTime.Now.Year
                                <i class="fa fa-copyright" aria-hidden="true"></i>
                                Desarrollado en JN WEB.
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </main>

    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>

</html>

JN_WEB/JN_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/favicon.png">
    <title>
        JN WEB
    </title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <link id="pagestyle" href="~/assets/css/material-dashboard.css?v=3.0.0" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.3.0/font-awesome-animation.min.css">
</head>

<body class="g-sidenav-show  bg-gray-200">
    <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <a class="navbar-brand m-0" href="@Url.Action("PantallaPrincipal","Home")">
                <img src="~/assets/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
                <span class="ms-1 font-weight-bold text-white">JN WEB</span>
            </a>
        </div>
        <hr class="horizontal light mt-0 mb-2">
        <div class="collapse navbar-collapse  w-auto  max-height-vh-100" id="sidenav-collapse-main">
            <ul class="navbar-nav">

                @if (Context.Session.GetString("RolUsuario").ToString() == "1")
                {
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("ConsultarUsuarios","Usuario")">
                            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                                <i class="material-icons opacity-10">dashboard</i>
                            </div>
                            <span class="nav-link-text ms-1">Usuarios</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white " href="../pages/tables.html">
                            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                                <i class="material-icons opacity-10">table_view</i>
                            </div>
                            <span class="nav-link-text ms-1">Cursos</span>
                        </a>
                    </li>
                }

                <li class="nav-item">
                    <a class="nav-link text-white " href="@Url.Action("ConsultarCursosUsuario", "Curso")">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">table_view</i>
                        </div>
                        <span class="nav-link-text ms-1">Pagar</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white " href="@Url.Action("ConsultarCursosUsuario", "Curso")">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-icons opacity-10">table_view</i>
                        </div>
                        <span class="nav-link-text ms-1">Mis Cursos</span>
                    </a>
                </li>
            </ul>
        </div>
    </aside>
    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">

        <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
            <div class="container-fluid py-1 px-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                        <li class="breadcrumb-item text-sm">Página Actual</li>
                        <li class="breadcrumb-item text-sm text-dark active" aria-current="page">@Context.Session.GetString("NombrePantalla")</li>
                    </ol>
                    <h6 style="font-weight:normal" class="mb-0">@Context.Session.GetString("NombreUsuario") / @Context.Session.GetString("NombreRolUsuario")</h6>
                </nav>

                <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                    <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                        <div class="input-group input-group-outline">
                            <label class="form-label"></label>
                            <input type="text" class="form-control" placeholder="Buscar">
                        </div>
                    </div>

                    <i class="fa fa-cart-plus fa-lg faa-tada animated-hover fixed-plugin-button-nav cursor-pointer"></i>&nbsp;&nbsp;&nbsp;
                    @Context.Session.GetString("Cantidad").ToString()&nbsp;&nbsp;&nbsp;
                    <i class="fa fa-money fa-lg faa-tada animated-hover fixed-plugin-button-nav cursor-pointer"></i>&nbsp;&nbsp;&nbsp;
                    @Context.Session.GetString("SubTotal").ToString()&nbsp;&nbsp;&nbsp;

                    <ul class="navbar-nav justify-content-end">
                        
                        <li class="nav-item dropdown pe-2 d-flex align-items-center">
                            <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-user fa-lg cursor-pointer" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;
                            </a>
                            <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                                <li class="mb-2">
                                    <a class="dropdown-item border-radius-md" href="@Url.Action("CambiarContrasennaUsuario", "Home")">
                                        <div class="d-flex py-1">
                                            <div class="my-auto">
                                                <i class="fa fa-unlock-alt fa-lg faa-tada animated-hover fixed-plugin-button-nav cursor-pointer" title="Cambiar Contraseña" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;
                                            </div>
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="text-sm font-weight-normal mb-1">
                                                    <span class="font-weight-bold">Cambiar Contraseña</span>
                                                </h6>
                                            </div>
                                        </div>
                                    </a>
                                </li>

                                <li class="mb-2">
                                    <a class="dropdown-item border-radius-md" href="@Url.Action("CerrarSesion", "Home")">
                                        <div class="d-flex py-1">
                                            <div class="my-auto">
                                                <i class="fa fa-sign-out fa-lg faa-tada animated-hover fixed-plugin-button-nav cursor-pointer" title="Cambiar Contraseña" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;
                                            </div>
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="text-sm font-weight-normal mb-1">
                                                    <span class="font-weight-bold">Cerrar Sesión</span>
                                                </h6>
                                            </div>
                                        </div>
                                    </a>
                                </li>                               
                            </ul>
                        </li>                        
                    </ul>

                </div>

            </div>
        </nav>

        <div class="container-fluid py-4">
            <div class="row min-vh-80 h-100">
                <div class="col-12">

                    @RenderBody()

                </div>
            </div>
            <footer class="footer pt-5">
                <div class="container-fluid">
                    <div class="row align-items-center justify-content-lg-between">
                        <div class="col-lg-6 mb-lg-0 mb-4">
                            <div class="copyright text-center text-sm text-muted text-lg-start">
                                @DateTime.Now.Year
                                <i class="fa fa-copyright" aria-hidden="true"></i>
                                Desarrollado en JN WEB.
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </main>
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>